[package]
name = "xsm_py"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "xsm_py"
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.72"
bytes = "1.4.0"
pyo3 = { version = "0.19.2", features = ["anyhow"] }
pyo3-asyncio = { version = "0.19.0", features = ["tokio", "tokio-runtime"] }
tokio = { version = "1.29.1", features = [
  "macros",
  "rt",
  "rt-multi-thread",
  "time"
] }
xsm = { path = "../xsm" }
